name: Build and release tauri app linux

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  tauri-build:
    name: Build and release tauri app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 16.x
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: sudo apt update && sudo apt install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libappindicator3-dev patchelf librsvg2-dev
      - run: npm install
      - run: npm run tauri:package
      
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: linux-release
          prerelease: false
          title: "Development Build"
          files: |
            src-tauri/target/release/bundle/appimage/weatherwatch_0.1.0_amd64.AppImage
            src-tauri/target/release/bundle/deb/weatherwatch_0.1.0_amd64.deb
