name: Build and release tauri app windows

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  tauri-build:
    name: Build and release tauri app
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: npm install
      - run: npm run tauri:package
      
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: windows-release
          prerelease: false
          title: "Development Build"
          files: |
            src-tauri/target/release/weatherwatch.exe
            src-tauri/target/release/bundle/msi/weatherwatch_0.1.0_x64.msi
